artifacts_root: artifacts

# Data Ingestion Configuration
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/1b4BiIO_Wx9bD5LUmjtKG0gGeTR-arI0L/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  train_data_dir: artifacts/data_ingestion/training
  test_data_dir: artifacts/data_ingestion/testing

# Base Model Preparation
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras

# Model Training
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras

# MLflow Configuration with DagsHub
mlflow:
  experiment_name: "Brain_Tumor_Classification"
  run_name_prefix: "mobilenetv2"
  tracking_uri: "https://dagshub.com/rahul22106/Brain-Tumor-Classification.mlflow"
  registered_model_name: "brain_tumor_classifier"
  dagshub_repo_owner: "rahul22106"
  dagshub_repo_name: "Brain-Tumor-Classification"
  tags:
    project: "Brain Tumor Detection"
    model_type: "Transfer Learning"
    base_model: "MobileNetV2"
    dataset: "Brain Tumor MRI"
    framework: "TensorFlow/Keras"
    author: "rahul22106"

evaluation:
  root_dir: artifacts/evaluation
  path_of_model: artifacts/training/model.keras
  test_data_dir: artifacts/data_ingestion/testing
  metric_file_name: scores.json